#!/bin/bash

# s03_report_config.sh
# Reporting settings for filtering step
# Alexey Larionov, 06Feb2016

pipeline_info=$(grep "^#" "${job_file}")
pipeline_info=${pipeline_info//"#"/}

echo "------------------- Pipeline summary -----------------"
echo ""
echo "${pipeline_info}"
echo ""
echo "--------- Data location and analysis settings --------"
echo ""
echo "data_server: ${data_server}"
echo "project_location: ${project_location}"
echo ""
echo "project: ${project}"
echo "dataset_name: ${dataset_name}"
echo "filter_name: ${filter_name}"
echo ""
echo "MIN_SNP_DP: ${MIN_SNP_DP}"
echo "MIN_SNP_QUAL: ${MIN_SNP_QUAL}"
echo "MIN_SNP_VQSLOD: ${MIN_SNP_VQSLOD}"
echo "SNP_TS: ${SNP_TS}"
echo ""
echo "MIN_INDEL_DP: ${MIN_INDEL_DP}"
echo "MIN_INDEL_QUAL: ${MIN_INDEL_QUAL}"
echo "MIN_INDEL_VQSLOD: ${MIN_INDEL_VQSLOD}"
echo "INDEL_TS: ${INDEL_TS}"
echo ""
echo "MIN_MIXED_DP: ${MIN_MIXED_DP}"
echo "MIN_MIXED_QUAL: ${MIN_MIXED_QUAL}"
echo "MIN_MIXED_VQSLOD: ${MIN_MIXED_VQSLOD}"
echo ""
echo "padding: ${padding}"
echo "ExcludeMultiAllelic: ${ExcludeMultiAllelic}"
echo "fa_threshold: ${fa_threshold}"
echo ""
echo "remove_project_folder: ${remove_project_folder}"
echo ""
echo "------------------ mgqnap settings -------------------"
echo ""
echo "mgqnap_user: ${mgqnap_user}"
echo "mgqnap_group: ${mgqnap_group}"
echo ""
echo "------------------- HPC settings ---------------------"
echo ""
echo "working_folder: ${working_folder}"
echo ""
echo "account_to_use: ${account_to_use}"
echo "time_to_request: ${time_to_request}"
echo ""
echo "----------------- Standard settings ------------------"
echo ""
echo "scripts_folder: ${scripts_folder}"
echo ""
echo "Tools"
echo "-----"
echo ""
echo "tools_folder: ${tools_folder}"
echo ""
echo "java7: ${java7}"
echo "gatk: ${gatk}"
echo ""
echo "bcftools: ${bcftools}"
echo "plot_vcfstats: ${plot_vcfstats}"
echo ""
echo "python_bin: ${python_bin}"
echo ""
echo "r_folder: ${r_folder}" 
echo "" 
echo "r_bin_folder: ${r_bin_folder}"
echo "r_lib_folder: ${r_lib_folder}"
echo "" 
echo "See note about using different R versions in the job description template"
echo ""
echo "Resources" 
echo "---------"
echo ""
echo "resources_folder: ${resources_folder}"
echo ""
echo "decompressed_bundle_folder: ${decompressed_bundle_folder}"
echo "ref_genome: ${ref_genome}"
echo ""
echo "nextera_folder: ${nextera_folder}"
echo "nextera_targets_intervals: ${nextera_targets_intervals}"
echo "nextera_targets_bed: ${nextera_targets_bed}"
echo ""
echo "Working sub-folders on HPC"
echo "--------------------------"
echo ""
echo "project_folder: ${project_folder}"
echo ""
echo "filtered_vcf_folder: ${filtered_vcf_folder}"
echo "logs_folder: ${logs_folder}"
echo "histograms_folder: ${histograms_folder}"
echo "all_vcfstats_folder: ${all_vcfstats_folder}"
echo "cln_vcfstats_folder: ${cln_vcfstats_folder}"
echo "" 