#!/bin/bash

# s03_report_settings.sh
# Report settings for genotyping gvcfs and assessing raw vcfs
# Alexey Larionov, 04Feb2016

pipeline_info=$(grep "^#" "${job_file}")
pipeline_info=${pipeline_info//"# "/}

echo "------------------- Pipeline summary -----------------"
echo ""
echo "${pipeline_info}"
echo ""
echo "--------- Data location and analysis settings --------"
echo ""
echo "data_server: ${data_server}"
echo "project_location: ${project_location}"
echo ""
echo "project: ${project}"
echo "sets: ${sets}"
echo "dataset: ${dataset}"
echo ""
echo "remove_project_folder: ${remove_project_folder}"
echo ""
echo "------------------ mgqnap settings -------------------"
echo ""
echo "mgqnap_user: ${mgqnap_user}"
echo "mgqnap_group: ${mgqnap_group}"
echo ""
echo "------------------- HPC settings ---------------------"
echo ""
echo "working_folder: ${working_folder}" 
echo "" 
echo "account_to_use: ${account_to_use}" 
echo "time_to_request: ${time_to_request}" 
echo "" 
echo "----------------- Standard settings ------------------"
echo ""
echo "scripts_folder: ${scripts_folder}"
echo ""
echo "maxAltAlleles: ${maxAltAlleles}"
echo "stand_call_conf: ${stand_call_conf}"
echo "stand_emit_conf: ${stand_emit_conf}"
echo ""
echo "Tools"
echo "-----"
echo "" 
echo "tools_folder: ${tools_folder}" 
echo "" 
echo "java7: ${java7}" 
echo "gatk: ${gatk}" 
echo "" 
echo "bcftools: ${bcftools}" 
echo "plot_vcfstats: ${plot_vcfstats}" 
echo "" 
echo "python_bin: ${python_bin}" 
echo "" 
echo "r_folder: ${r_folder}" 
echo "" 
echo "r_bin_folder: ${r_bin_folder}"
echo "r_lib_folder: ${r_lib_folder}"
echo "" 
echo "See note about using different R versions in the job description template"
echo ""
echo "Resources" 
echo "---------"
echo ""
echo "resources_folder: ${resources_folder}"
echo ""
echo "decompressed_bundle_folder: ${decompressed_bundle_folder}"
echo "ref_genome: ${ref_genome}"
echo "hapmap: ${hapmap}"
echo "omni: ${omni}"
echo "phase1_1k_hc: ${phase1_1k_hc}"
echo "dbsnp_138: ${dbsnp_138}"
echo "dbsnp_138_sites129: ${dbsnp_138_sites129}"
echo "mills: ${mills}"
echo ""
echo "nextera_folder: ${nextera_folder}"
echo "nextera_targets_intervals: ${nextera_targets_intervals}"
echo "nextera_targets_bed: ${nextera_targets_bed}"
echo ""
echo "fa_mask_folder: ${fa_mask_folder}"
echo "fa_mask_90: ${fa_mask_90}"
echo "fa_mask_95: ${fa_mask_95}"
echo "fa_mask_99: ${fa_mask_99}"
echo "fa_mask_100: ${fa_mask_100}"
echo ""
echo "Working folders"
echo "---------------"
echo ""
echo "project_folder: ${project_folder}"
echo ""
echo "raw_vcf_folder: ${raw_vcf_folder}"
echo "logs_folder: ${logs_folder}"
echo "vqsr_folder: ${vqsr_folder}"
echo "all_vcfstats_folder: ${all_vcfstats_folder}"
echo "cln_vcfstats_folder: ${cln_vcfstats_folder}"
echo "histograms_folder: ${histograms_folder}"
echo "" 